// project_model.dart
import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart'; // Import for @freezed

// These two lines are crucial for Freezed code generation.
// They tell Dart's build_runner to generate files for this part.

part 'model.g.dart'; 
part 'model.freezed.dart';  // For JSON serialization with Freezed

/// Represents a single project that users can contribute to.
/// This model holds all the necessary information for a project.
///
/// The @freezed annotation indicates that this class will be processed by
/// the Freezed code generator to create immutable data classes with
/// boilerplate like copyWith, equals, hashCode, and toString.
@freezed
class Project with _$Project { // CORRECTED: Added 'with _$Project'
  /// Factory constructor for the Project class.
  /// When using Freezed, you define your constructor as a factory and
  /// Freezed generates the actual implementation.
  /// All fields are required to create a Project instance.
  const factory Project({
    required String id, // Unique identifier for the project
    required String title, // Title of the project
    required String description, // A brief description of the project
    required double targetAmount, // The total amount of money targeted for the project
    required double currentAmount, // The current amount of money contributed to the project
    required String imageUrl, // URL for an image representing the project (for carousel)
  }) = _Project; // CORRECTED: Changed to a factory constructor with '= _Project'

  /// Factory constructor to create a Project object from a JSON map.
  /// This method is automatically generated by Freezed when you include
  /// 'part 'project_model.g.dart';' and run build_runner.
  /// It uses json_serializable under the hood.
  factory Project.fromJson(Map<String, dynamic> json) => _$ProjectFromJson(json);
  
  @override
  // TODO: implement currentAmount
  double get currentAmount => throw UnimplementedError();
  
  @override
  // TODO: implement description
  String get description => throw UnimplementedError();
  
  @override
  // TODO: implement id
  String get id => throw UnimplementedError();
  
  @override
  // TODO: implement imageUrl
  String get imageUrl => throw UnimplementedError();
  
  @override
  // TODO: implement targetAmount
  double get targetAmount => throw UnimplementedError();
  
  @override
  // TODO: implement title
  String get title => throw UnimplementedError();
  
  @override
  Map<String, dynamic> toJson() {
    // TODO: implement toJson
    throw UnimplementedError();
  }

  // REMOVED: The manual toJson() method is no longer needed as Freezed/json_serializable generates it.
  // REMOVED: The manual copyWith() method is no longer needed as Freezed generates it.
}